### ISSUE TITLE
Create initial sphinx documentation

### ISSUE THREAD

**Issue by craig-willis** [cheese-hub/cheesehub#17]
Create an initial Sphinx documentation project

**Comment by craig-willis** [comment]
Created repo https://github.com/cheese-hub/cheesehub with sphinx-generated docs using bootstrap theme.   Also now available via https://cheesehub.readthedocs.io/

**Comment by craig-willis** [comment]
@BenGalewsky for review.  Sorry.

**Comment by BenGalewsky** [comment]
Yep, looks good
