### ISSUE TITLE
Refactor arpspoof scenario

### ISSUE THREAD

**Issue by craig-willis** [cheese-hub/cheesehub#25]
The goal is to convert the hacker image to a Jupyter notebook, remove unnecessary dependencies, upgrade base images.

* https://github.com/cheese-hub/arpspoof
* https://github.com/cheese-hub/base-notebook

**Comment by rkalyanapurdue** [comment]
@craig-willis this one is ready for review as well. Please take a look when you get a chance.

**Comment by craig-willis** [comment]
Sorry for the delay.  I've decided to put some comments in an external document, since some of my feedback really requires additional discussion.

https://docs.google.com/document/d/1ry7lkx6FsRBhDVr-RvXAi6iifpLgO6FQk0wcUMalYQs/edit

**Comment by rkalyanapurdue** [comment]
Thanks Craig! Let me take a look at this and we can discuss in our next meeting...

**Comment by rkalyanapurdue** [comment]
Here's an overview of each of the containers:

1. Hacker
  a. Based on Jupyter's base notebook
  b. Adds network tools to configure iptables, ping, etc.
  c. Adds a Python 2 kernel to Jupyter to run SSLStrip (only supports Python 2.x so far)
  d. Install SSLStrip and its dependencies
  e. Primary hacker notebook with step-by-step instructions for ArpSpoof attack

2. Victim
  a. Based on Ubuntu 18.04 VNC image
  b. Adds networking tools to ping, traceroute to server, etc.
  c. Create and use a default non-root "victim" user

3. Server
  a. Based on Jupyter's base notebook for consistency
  b. Hosts a simple SSL-enabled web application built using Flask (requires SSL module, rewrite to redirect to HTTPS)
  c. Uses Apache 2, replaces default web app with the Flask-based one (uses site config to setup new default)
 d. Uses supervisor to start both Apache and notebook server
 e. Notebook has barebones instructions to determine IP for use in victim and hacker

**Comment by craig-willis** [comment]
Per 12/20 call, needs one more review pass and updated README.
