### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by craig-willis** [cheese-hub/cheesehub#38]
Setup Google Analytics for CHEESE-Hub. For now, we'll just track the primary instance.

**Comment by bodom0015** [comment]
A new Google Analytics application/property has been configured for the CHEESEhub instance.

Those with proper access can sign into the Analytics Dashboard at https://analytics.google.com and choose the CHEESEhub property (from the dropdown at the top-left) to see collected metrics
